name: Build and Push Fastapi Docker Image

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/docker-labs:latest
        # build-args:
        #   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: SSH into GCE and deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.GCE_HOST }}
        username: ${{ secrets.GCE_USERNAME }}
        key: ${{ secrets.GCE_SSH_KEY }}
        script: |
          docker stop fast-api-container || true
          docker rm fast-api-container || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/docker-labs:latest
          docker run -d --name fast-api-container -p 8000:80 -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} ${{ secrets.DOCKER_USERNAME }}/docker-labs:latest