name: Build and Push Fastapi Docker Image

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/docker-labs:latest

    - name: SSH into GCE and deploy
      env:
        GCE_HOST: ${{ secrets.GCE_HOST }}
        GCE_USERNAME: ${{ secrets.GCE_USERNAME }}
        GCE_SSH_KEY: ${{ secrets.GCE_SSH_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo "${GCE_SSH_KEY}" > /tmp/gce_ssh_key
        chmod 600 /tmp/gce_ssh_key
        ssh -o StrictHostKeyChecking=no -i /tmp/gce_ssh_key ${GCE_USERNAME}@${GCE_HOST} << EOF
          docker stop fast-api-container || true
          docker rm fast-api-container || true
          docker pull ${DOCKER_USERNAME}/docker-labs:latest
          docker run -d --name fast-api-container -p 8001:8001 -e OPENAI_API_KEY=${OPENAI_API_KEY} ${DOCKER_USERNAME}/docker-labs:latest
        EOF